services:
  mysql80:
    image: mysql:8.0
    container_name: mysql80
    ports:
      - "${MYSQL_80_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_80_ROOT_PASSWORD}"
    volumes:
      - ${MYSQL_DATA_ROOT}/8.0:/var/lib/mysql
      - ./config/mysql/8.0/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - net
    restart: unless-stopped
    labels:
      - "phpbox-service=mysql"
      - "phpbox-version=8.0"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
