services:
  php84:
    image: 
    container_name: php84
    volumes:
      - ${WWW_ROOT}:/var/www
      - ./config/php/8.4/php.ini:/usr/local/etc/php/php.ini:ro
      - ./logs/php:/var/log/php:rw
    networks:
      - net
    restart: unless-stopped
    labels:
      - "phpbox-service=php"
      - "phpbox-version=8.4"
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
